apiVersion: apps/v1
kind: Deployment
metadata:
  name: ankiba-nginx-deployment
  labels:
    role: web
spec:
  replicas: 1
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
    spec:
      nodeSelector:
        role: worker
      containers:
      - name: nginx
        image: ___IMAGE_URL___@___IMAGE_DIGEST___
        ports:
        - containerPort: 80
