apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: staging
  app.kubernetes.io/managed-by: kustomize
namespace: develop

images:
- digest: sha256:90c94e01c2926be489f1b8ad2277f16de423f85feb8999d7dba01f22e6b641ab
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: ghcr.io/unimarist/ankiba-web

resources:
- ../../base
