apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: production
  app.kubernetes.io/managed-by: kustomize
namespace: production

resources:
- ../../base
