apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-pipelines.yaml
  - tekton-triggers.yaml
  - interceptors.yaml
  - tekton-admin-sa.yaml
  - tekton-admin-triggers-rbac.yaml
  - git-clone-task.yaml
  - buildah-task.yaml
  - kustomize-task.yaml
