apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develop-ankiba
  namespace: argocd
  labels:
    app: ankiba
    environment: develop
spec:
  destination:
    namespace: develop
    server: infra_user@ankiba-cluster
  project: ankiba
  source:
    kustomize:
    path: ankiba/ap/base
    repoURL: https://github.com/unimarist/k8s_manifest.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true
