apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ankiba-w-el-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie" # セッション管理
    nginx.ingress.kubernetes.io/limit-rps: "5" # DDOS対策
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /el/ankiba-web
        pathType: Prefix
        backend:
          service:
            name: el-ankiba-w-listener
            port:
              number: 8080
