apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-admin-sa.yaml
  - tekton-admin-triggers-rbac.yaml
  - git-clone-task.yaml
  - ankiba-buildah-task.yaml
  - ankiba-kustomize.yaml
  - ankiba-build-template.yaml
  - ankiba-build-binding.yaml
  - ankiba-build-pipeline.yaml
  - ankiba-listener.yaml
  - github-el-ingress.yaml
  - ankiba-web-build-template.yaml
  - ankiba-web-build-binding.yaml 
  - ankiba-web-build-pipeline.yaml
  - ankiba-web-listener.yaml
  - ankiba-web-el-ingress.yaml
